projects:
  introToAmplify:
    schemaPath: frontend/graphql/schema.json
    includes:
      - frontend/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: frontend/graphql
